services:
  awg-tg-bot:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256MB
    env_file:
      .env
    networks:
      - awg-tg-bot
    restart: unless-stopped

networks:
  awg-tg-bot:
